function Inversiones() {
    return (
        <section id="inversiones" className="padded">
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti quos dignissimos, ex perspiciatis repellendus vero molestias nisi cumque eaque cum hic ipsam porro eius numquam dolorum laudantium! Aspernatur commodi reiciendis odio ad iure eligendi officiis odit esse molestiae possimus vitae totam, error neque. Culpa consequatur omnis velit quisquam provident, sunt reiciendis numquam distinctio alias ut in, eum labore rem dolorum? Aspernatur laboriosam, dolores reprehenderit maxime accusantium quaerat sint ab iste eos consectetur non amet doloribus laudantium facere recusandae cum totam.</p>
                <p>Assumenda libero aliquid, totam sunt atque porro repellendus facilis saepe animi nam necessitatibus ea, laudantium laboriosam alias eligendi maxime ut modi suscipit reiciendis explicabo laborum? Quis quia minima exercitationem iure commodi cumque eaque itaque possimus nam incidunt porro voluptatem voluptatum eius mollitia eum rerum aliquid magnam, beatae aperiam laudantium. Error, sapiente. Ex minima voluptatum assumenda quia commodi dicta minus dolores explicabo magni omnis tempore voluptatibus pariatur ut, inventore earum eius provident quae blanditiis? Dicta, rem voluptates vel rerum ea laborum!</p>
                <p>Natus rerum dolore suscipit commodi impedit dolor praesentium eius ullam illo omnis soluta sint quia saepe, quae pariatur accusantium repudiandae dicta ipsum tenetur quis beatae odit quos corporis aliquid! Non mollitia maiores nostrum quia! Alias obcaecati accusamus saepe quasi fugit ea veniam non nam, officiis sit delectus ipsum dolores amet cumque vero suscipit doloribus rerum! Impedit quasi assumenda ratione ducimus, ad ex ipsam quia officiis, dignissimos eligendi provident perferendis, nemo facilis cupiditate praesentium ipsa in? Nostrum nulla possimus sit ullam!</p>
                <p>Soluta tenetur magni fugiat nobis exercitationem blanditiis optio est maxime! Rem velit magnam maxime odio rerum, ut autem nostrum? Nam, sint officia voluptatibus, assumenda atque esse perferendis commodi tempore blanditiis cupiditate iste! Voluptatibus ratione iusto commodi tempore recusandae nihil! Illum placeat perspiciatis mollitia officia, consectetur aperiam dolorum, officiis quis ab praesentium tempora temporibus. Natus dolorem, accusamus veniam in modi iste perspiciatis labore repellat dignissimos dolore incidunt saepe, voluptates nemo inventore iusto ratione aut delectus maxime molestias! Exercitationem cum maxime sequi?</p>
                <p>Praesentium, eum. Consequatur voluptatem repellat magni eligendi facere, minima dolorum quasi porro quo aspernatur error voluptas? Omnis atque corrupti labore et officia aliquid rem! Facere corporis quam similique expedita repellat unde exercitationem est? Illum molestias impedit mollitia, veritatis distinctio perferendis ipsa? Dolorum qui voluptas reprehenderit magni recusandae saepe unde nisi eos dignissimos at nobis dolorem, ex aliquam sunt placeat, quia fugiat expedita, quod enim deserunt modi. Tempore minima quo, ullam excepturi neque doloremque error nostrum, vel iusto corporis debitis dolores.</p>
                <p>Deleniti voluptatum aperiam eius neque mollitia soluta unde, quaerat enim cum eum velit praesentium tempore beatae id corporis obcaecati quibusdam a. Explicabo quae, odio porro non, maxime esse veniam quasi hic iste laborum natus! Doloremque eum iste ducimus nihil explicabo nisi consectetur cumque, dolorem voluptate quod repellat saepe aliquam placeat expedita quisquam quo ratione mollitia sint asperiores, illum, corporis a ut. Aspernatur id ipsum ullam ratione, nostrum adipisci nulla. Quasi harum earum error aperiam, distinctio alias. Asperiores eligendi qui officiis!</p>
            </div>
        </section>
    )
}

export default Inversiones